
services:
  server:
    build:
      context: .
      dockerfile: ./.dockerfile
    container_name: ewallet-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app         # sync local file ke container
      - /app/node_modules  # mencegah overwrite node_modules container
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    container_name: ewallet-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: e_wallet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
